# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-20 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dragonfly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='owner',
        ),
    ]
