# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-15 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonfly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
