# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-22 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonfly', '0002_remove_sensor_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.TextField(default=b''),
        ),
    ]
