# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-08 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonfly', '0003_sensor_sensor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='units',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
