# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-13 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonfly', '0005_auto_20170310_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_reading',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
