# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-17 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonfly', '0006_sensor_last_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='max_value',
            field=models.FloatField(default=1024),
        ),
        migrations.AddField(
            model_name='sensor',
            name='min_value',
            field=models.FloatField(default=0),
        ),
    ]
