# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonfly', '0007_auto_20170316_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='last_reading',
            field=models.FloatField(blank=True),
        ),
    ]
