# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonfly', '0008_auto_20170319_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='last_reading',
            field=models.FloatField(default=0),
        ),
    ]
