# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-05 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragonfly', '0009_auto_20170319_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='last_reading',
            field=models.FloatField(),
        ),
    ]
